In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
#NumPY's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3.3], [4,5,6.4]])

a3= np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])


In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [ ]:
a1.dtype,a2.dtype,a3.dtype

In [ ]:
a1.size, a2.size,a3.size

In [ ]:
type(a1),type(a2),type(a3)

In [ ]:
#Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

## 2. Creating arrays 

In [12]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [ ]:
sample_array.dtype

In [13]:
#What wanted to create a numpy array that was already filled?

ones=np.ones((2,2))

In [ ]:
ones

In [ ]:
ones.dtype

In [14]:
type(ones)

numpy.ndarray

In [15]:
zeros=np.zeros((4,4))

In [ ]:
zeros

In [16]:
range_array=np.arange(0,10,2)

In [ ]:
range_array

In [17]:
random_array = np.random.randint(0,10,size=(3,5))
random_array


array([[1, 3, 3, 9, 7],
       [8, 3, 9, 3, 9],
       [0, 6, 9, 2, 3]])

In [ ]:
random_array.size

In [ ]:
random_array.shape

In [18]:
random_array_2=np.random.random((5,3))

In [ ]:
random_array_2

In [ ]:
random_array_2.shape
#result is (rows,columns). 

In [19]:

random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.08019759, 0.49692221, 0.86444239],
       [0.31593008, 0.31302706, 0.04911969],
       [0.24690387, 0.50740698, 0.27989781],
       [0.08443723, 0.07017414, 0.20658007],
       [0.73346381, 0.70633003, 0.58440826]])

In [21]:
#Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4
#How would you find unique elements in random arrays? 

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [22]:
np.random.seed(seed=7)
# For someone else to use our notebook and get same results in our experiments. 
random_array_5=np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [23]:
random_array_5=np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3.Viewing arrays and Matrices

In [ ]:
np.unique(random_array_4)

In [ ]:
a1[0]

In [ ]:
a2[0]

In [ ]:
a2.shape

In [ ]:
a2

In [ ]:
a2[1]

In [ ]:
a3[:]

In [ ]:
a3[:2,:2,:2]
#first two values of the above arrays

In [24]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [25]:
a4.shape,a4.ndim
#shape is two by three by four by five, and dim is the number of dims.

((2, 3, 4, 5), 4)

In [26]:
#how would we get first four numbers of one of the vectors? 
#Numpy displays from the outside integer inward - 
#get the first 4 numbers of the inner most array
a4[:,:,:,:4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

## 4. Manipulate Arrays

## Arithmetic

In [ ]:
a1

In [ ]:
ones = np.ones(3)
ones

In [ ]:
a1 + ones

In [ ]:
a1 - ones

In [ ]:
a1 * ones

In [ ]:
a2

In [ ]:
a1 * a2
# takes the top row multiplies it by the top row of a2.

In [ ]:
3 * 3.3

In [ ]:
a2 * a3


## broadcast describes how numpy treats arrays with different shapes during arithmetic operations. 
## we are trying to use arithmetic on arrays with different shapes. 
## Subject to current constraints the smaller array is "broadcast" across the larger array so that they have compatible shapes
## Numpys broadcasting rule relaxes this constraint when the arrays' shapes meet certain constraints

## When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works
## its way forward. Two dimensions are compatible when 
## 1. They are equal, or
## 2. one of them is 1. 

In [ ]:
#How can I reshape a2 to be compatible with a3? Search:"How to reshape Numpy array"
a2 * a3

In [ ]:
a1 /ones

In [ ]:
a2 /a1

In [ ]:
#Floor division removes the decimals (rounds down)
a2 // a1 

In [ ]:
a2 ** 2 
#to the power of 2

In [ ]:
np.square(a2)
#using ** or square depends on teh workflow. 

In [ ]:
#adds arguments elements wise
np.add(a1,ones)

In [ ]:
a1 % 2

In [ ]:
a1 / 2
#numpy modulo. Returen element-wise remainder of division

a2 % 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)
#Exponential of everything in an array

In [ ]:
np.log(a1)

## Aggregation 

<p>Aggregation = performing the same operation on a number of things</p>

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
type(a1)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

## Use Python's methods (`sum()`) on Python datatypes and use 
## NumPy's methods on NumPy arrays(`np.sum()`).

In [ ]:
#Create a massive NumPy array
massive_array = np.random.random(10000)
massive_array.size

In [ ]:
massive_array[:100]

In [ ]:
%timeit 
#times how long a particular line of code takes to run
%timeit sum(massive_array)
%timeit np.sum(massive_array)
#if working with numpy data, use Numpy methods. 
# if working with datatypes use Python methods.

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
np.std(a2)
#standard deviation -measure of how spread out a group of numbers is from the mean. along specified axis

In [ ]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
#Lower variance = lower range of numbers
np.var(a2)

In [ ]:
#standard deviation = squareroot of variance. Same result as output 53. 
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var 
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array
                               #std is the standard difference the number is away from the mean

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [27]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

## <p>Can see from chart here that the spread of numbers, more white space, more numbers are closer to zero.</p>

In [ ]:
plt.hist(low_var_array)
plt.show()


## spread is similar across the whole thing. 

## 5. Reshaping and Transpose 

In [ ]:
a2 


In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
#reshape is a method you can call on any array, returns an array containing the same data with a new shape. 

In [ ]:
#broadcasting = one of the rules of this, NumPy compares the shape of the arrays element wise. Two dimensions are compatible if 
# one of the arrays is equal or one is 1. 

#reshape the a2 array. ADD A DIMENSION. 

In [ ]:
a2.reshape(2,3,1).shape

In [ ]:
a3.shape

In [ ]:
#one of these has one in the array. 
a2_reshape = a2.reshape(2,3,1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
a2.shape

In [ ]:
#Transpose
a2.T

In [ ]:
#Transpose
#What has changed? The axis' has been switched. 
a2.T.shape

In [ ]:
a2.T

In [ ]:
a2.T

In [ ]:
a2.shape

In [ ]:
a2

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

In [ ]:
#When would we use a Transpose


## Dot Product 

In [ ]:
np.random.seed(0)

mat1=np.random.randint(10, size=(5,3))
mat2=np.random.randint(10,size=(5,3))

In [ ]:
mat2

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
#Elemet-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
#Dot product
np.dot(mat1,mat2)

In [ ]:
#How to fix the above error
# Use a transpose
mat1.T

In [ ]:
mat1.T.shape, mat2.T.shape

mat3=np.dot(mat1,mat2.T)
mat3

mat3

In [ ]:
mat3=np.dot(mat1,mat2.T)
mat3

In [ ]:
mat3.shape

## Dot Product Example (nut butter sales)

In [29]:
np.random.seed(0)
#Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [33]:
pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 54.1 MB/s eta 0:00:0000:010:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 24.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 26.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [34]:
import pandas as pd

In [35]:
#Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed","Thurs", "Fri"],
                           columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [36]:
#Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [38]:
prices.shape

(3,)

In [40]:
#Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"],
                            columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [41]:
prices

array([10,  8, 12])

In [45]:
sales_amounts.shape

(5, 3)

In [43]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [47]:
#Transpose because Shapes arent aligned
total_sales=prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [53]:
#Create daily sales
butter_prices.shape,weekly_sales.shape

((1, 3), (5, 3))

In [51]:
#Want to combuine daily sales and weekly sales in a dataframe
weekly_sales.shape

(5, 3)

In [55]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [58]:
#how to get on the right hand side of the dataframe? new column?
#Not the right shape. doesnt work
weekly_sales["Total($)"]=daily_sales
weekly_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total($)

In [59]:
daily_sales.shape

(1, 5)

In [60]:
weekly_sales.shape

(5, 3)

In [61]:
weekly_sales["Total($)"]=daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total($)
Mon               12             15              0       240
Tues               3              3              7       138
Wed                9             19             18       458
Thurs              4              6             12       232
Fri                1              6              7       142

### Comparison Operators

In [62]:
a1

array([1, 2, 3])

In [63]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.4]])

In [64]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [66]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [67]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [68]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [69]:
a1 > 5

array([False, False, False])

In [70]:
a1 < 5

array([ True,  True,  True])

In [71]:
a1 == a1

array([ True,  True,  True])

In [72]:
a1 == a2 

array([[ True,  True, False],
       [False, False, False]])

## 5. Sorting Arrays

In [75]:
random_array.shape

(3, 5)

In [76]:
np.sort(random_array)
#returns an assorted copy of an array

array([[1, 3, 3, 7, 9],
       [3, 3, 8, 9, 9],
       [0, 2, 3, 6, 9]])

In [77]:
np.argsort(random_array)
#

array([[0, 1, 2, 4, 3],
       [1, 3, 0, 2, 4],
       [0, 3, 4, 1, 2]])

In [78]:
a1

array([1, 2, 3])

In [79]:
np.argsort(a1)

array([0, 1, 2])

In [80]:
np.argmin(a1)

0

In [81]:
np.argmax(a1)

2

In [83]:
np.argmax(random_array)
#Where the maximum value on axis = 0

3

In [86]:
random_array

array([[1, 3, 3, 9, 7],
       [8, 3, 9, 3, 9],
       [0, 6, 9, 2, 3]])

In [88]:
np.argmax(random_array, axis=1)

array([3, 2, 2])

In [87]:
np.argmax(random_array, axis=0)

array([1, 2, 1, 0, 1])

## 6. Practical Example - NumPy in Action

<img src ="images/Tura.jpg"/>

In [110]:
#Turn an image into a NumPy array
from matplotlib.image import imread

In [120]:
tura = imread("images/Tura.jpg")
print(type(tura))

<class 'numpy.ndarray'>


In [122]:
tura.size, tura.shape, tura.ndim


(9725952, (2048, 1583, 3), 3)

imread takes picture and found pixel values and their color values and store them in the array. 


<img src="images/eyes.jpg"/>

In [123]:
eyes = imread("images/eyes.jpg")
print(type(eyes))

<class 'numpy.ndarray'>


In [124]:
eyes

array([[230, 229, 229, ..., 230, 231, 231],
       [229, 229, 228, ..., 229, 230, 230],
       [228, 228, 228, ..., 229, 229, 230],
       ...,
       [243, 242, 241, ..., 240, 240, 241],
       [243, 242, 241, ..., 240, 240, 241],
       [244, 243, 241, ..., 239, 240, 240]], dtype=uint8)

In [125]:
eyes[:1]

array([[230, 229, 229, 228, 228, 227, 227, 227, 224, 225, 225, 226, 226,
        225, 224, 224, 224, 224, 223, 224, 225, 227, 229, 230, 231, 231,
        231, 230, 227, 225, 222, 220, 225, 225, 225, 226, 226, 226, 227,
        227, 227, 228, 230, 232, 233, 233, 232, 232, 232, 233, 233, 234,
        234, 233, 233, 232, 233, 233, 232, 230, 228, 228, 230, 232, 230,
        230, 230, 230, 230, 229, 229, 229, 228, 230, 233, 234, 234, 234,
        235, 237, 236, 235, 233, 231, 230, 230, 230, 231, 230, 230, 231,
        231, 231, 231, 231, 232, 232, 233, 234, 235, 235, 235, 235, 235,
        231, 232, 233, 234, 235, 236, 236, 236, 234, 233, 233, 232, 232,
        233, 233, 234, 234, 235, 235, 236, 236, 235, 235, 234, 236, 235,
        235, 234, 234, 235, 235, 236, 235, 235, 234, 236, 238, 238, 237,
        235, 234, 231, 229, 228, 229, 230, 230, 230, 232, 232, 232, 232,
        233, 234, 235, 236, 235, 234, 234, 233, 233, 234, 234, 235, 235,
        235, 235, 235, 235, 235, 235, 235, 236, 236