In [1]:
import numpy as np

In [6]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [12]:
a2=np.array([[2,5,2],[2,3,5]])
a2

array([[2, 5, 2],
       [2, 3, 5]])

In [23]:
a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])

In [24]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
a1.shape,a2.shape,a3.shape

((3,), (2, 3), (2, 3, 3))

In [26]:
a1.ndim, a2.ndim,a3.ndim

(1, 2, 3)

In [27]:
import pandas as pd

In [29]:
df=pd.DataFrame(a2)
df

0  1  2
0  2  5  2
1  2  3  5

In [32]:
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
random_array=np.arange(0,100,3)
random_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])